server:
  port: 8082

spring:
  application:
    name: profile
  datasource:
    password: 'root'
    url: jdbc:postgresql://localhost:5432/profile
    username: 'anillama'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    removeProfile: removeProfile.queue
    getNameProfile: getNameProfile.queue
    createProfileFromQueue: createProfileFromQueue.queue
  routing-keys:
    internal-removeProfile: internal.removeProfile.routing-key
    internal-getNameProfile: internal.getNameProfile.routing-key
    internal-createProfileFromQueue: internal.createProfileFromQueue.routing-key