apiVersion: apps/v1
kind: Deployment
metadata:
  name: sessionmanagement
  labels:
    app: sessionmanagement
spec:
  replicas: 1
  template:
    metadata:
      name: sessionmanagement
      labels:
        app: sessionmanagement
    spec:
      containers:
        - name: sessionmanagement
          image: anillama/sessionmanagement:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: sessionmanagement