apiVersion: apps/v1
kind: Deployment
metadata:
  name: userproject
  labels:
    app: userproject
spec:
  replicas: 1
  template:
    metadata:
      name: userproject
      labels:
        app: userproject
    spec:
      containers:
        - name: userproject
          image: anillama/userproject:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: userproject